### ISSUE TITLE
what's the purpose of this repo?

### ISSUE THREAD

**Issue by nichdiekuh** [project-fifo/fifo.js#2]
Hi,

I was looking for a nodejs package for the fifo API and found this, but I'm not sure wether this package is ready for production or not. It's lacking a basic description and docs.

What's the purpose of this repo?

**Comment by dang0ld** [comment]
We are using this in production - I will work on adding a basic description and docs.

Installation: 
npm install node-fifo

Basic Usage:
require('node-fifo');

var token = FiFo.connect(fifo_url, fifo_username, fifo_password);
token.then(function(obj) {
  var session = FiFo.sessionTest(obj.token, obj);
  session.then(function(sess) {
    console.log(sess);
  });
};

**Comment by nichdiekuh** [comment]
Thanks for your quick reply! 
In vers 0.7 I can generate API tokens. I'd rather use the API token instead of username+password in scripts. Is that possible too?

**Comment by dang0ld** [comment]
That is not present in this version, but I will work on getting that in here also. Still working on final items from our weekend production transition from 0.6.2 -> 0.7 :)

I'll open a new issue for that one.. thanks.
