### ISSUE TITLE
Add support for fifo 0.7.0 API tokens as alternative to username/pw logins

### ISSUE THREAD

**Issue by dang0ld** [project-fifo/fifo.js#3]

**Comment by dang0ld** [comment]
@nichdiekuh

**Comment by nichdiekuh** [comment]
:+1:

**Comment by dang0ld** [comment]
OK, this is live in 0.2.6 - if you pass a missing username ('' or undefined), and an api-key as a password, it will work.

839e147e4efacbb6bbf7dc133bff8cc3323773a0
