### ISSUE TITLE
Config is not defined

### ISSUE THREAD

**Issue by nichdiekuh** [project-fifo/fifo.js#4]
Hello,

it looks like the commit a1930c1accffa180315e199dc7088a94d42845d4 broke the lib.I am getting the following error:
`
fifo/node_modules/node-fifo/lib/fifo.js:6
var apiVersion = (Config && ('FiFo' in Config) && Config.FiFo.length) ? Config
                  ^
ReferenceError: Config is not defined
 `

**Comment by dang0ld** [comment]
Can you confirm that reverting the line to a string corrects your problem?

I only ask, because the Config pre-defined global was also used elsewhere, and it probably would have broken your setup if you did not define Config, regardless of this newer change:

https://github.com/project-fifo/fifo.js/blob/27a8d7e6db9c1e78f7028c21fbed40796a2f282d/lib/fifo.js#L562

Regardless, I will have it default to some string if Config does not exist.

**Comment by nichdiekuh** [comment]
Nope, changing line #7 doesn't fix the issue. The line you mention has the same issue and I'm wondering where `Config` is supposed to be defined.

**Comment by nichdiekuh** [comment]
Also, the lib doesn't export anything. FiFo.connect() for instance is undefined when you require the lib. Are you using any new node-features I'm not aware of or is this lib broken?

**Comment by dang0ld** [comment]
Yes, it absolutely works, it has been in production use for years.

I apologize for leaving off some important usage information.

Please see the updated README here: a1973ef8e98a6d9e92b99ecf75dcfff622d82f85.

**Comment by nichdiekuh** [comment]
I am sorry, but from point of view this isn't working and your example is wrong.

In the readme you are using the require function the way it's used in PHP. This is JavaScript and as far as I understand node, everything in a required module is inside its own scope unless it's exported with for instance `module.exports = FiFo`.
The same applies to the `Config` object example in the readme. There's no "global scope" wich makes `Config` accessible in a required module, unless you pass it to a function/object from that required module.

Please tell me whether I totally misunderstood everything. ;)

**Comment by dang0ld** [comment]
You are correct again, I left out this important portion:

```
var Config = global.Config = {
```

Yes, this was made years ago and might not use the best design philosophy, but I assure you it works and is being used at this exact moment.

The code will be reworked in the future, but that moment is not today. Here's the best way to get it working:

173374f523afb9f6bfcf7d1bb4d8e8aae60e4e85

**Comment by nichdiekuh** [comment]
I got it working (look at my fork), but I wanted to point to out that this module can't be used like any other module atm. Hopefully this ticket saves someone else some time.

**Comment by dang0ld** [comment]
Feel free to submit a PR!

Thanks for your interest.
